data: helloworld

my:
  list:
     values: one,two,three
   
dbValues: "{connectionString:'http://localhost',userName:'foo',password:'pass'}"

db:
  connection: connection-string
  host: 127.0.01
  port: 8080
  
management.endpoints.web.exposure.include: "*"
spring.profiles.active: test